# Generated by Django 4.1.5 on 2023-01-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Регистр', 'verbose_name_plural': 'Регистр'},
        ),
    ]
