# Generated by Django 4.1.5 on 2023-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dolists', '0006_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_complete',
            field=models.BooleanField(default=True, verbose_name='Завершено'),
        ),
    ]
