# Generated by Django 4.1.5 on 2023-01-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dolists', '0007_alter_todolist_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.DeleteModel(
            name='Completed',
        ),
    ]
